[2024-06-07T14:39:30.560+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:30.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:39:30.636+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:30.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:30.742+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:30.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:39:30.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:31.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.776 seconds
[2024-06-07T14:39:41.806+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:41.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:39:41.826+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:41.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:41.857+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:41.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:39:41.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:41.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.100 seconds
[2024-06-07T14:39:52.207+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:52.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:39:52.343+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:52.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:52.653+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:39:52.574+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:39:52.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:39:52.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.570 seconds
[2024-06-07T14:40:03.049+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:03.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:40:03.052+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:03.051+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:03.344+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:03.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:40:03.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:03.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.832 seconds
[2024-06-07T14:40:14.063+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:14.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:40:14.066+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:14.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:14.112+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:14.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:40:14.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:14.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.301 seconds
[2024-06-07T14:40:24.729+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:24.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:40:24.806+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:24.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:25.265+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:25.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:40:25.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:25.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.974 seconds
[2024-06-07T14:40:36.676+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:36.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:40:36.680+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:36.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:36.715+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:36.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:40:36.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:36.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.266 seconds
[2024-06-07T14:40:47.459+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:47.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:40:47.925+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:47.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:48.994+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:40:48.525+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:40:48.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:40:49.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.759 seconds
[2024-06-07T14:41:01.845+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:01.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:01.848+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:01.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:02.015+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:01.860+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:02.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:02.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.314 seconds
[2024-06-07T14:41:13.770+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:13.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:13.781+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:13.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:13.842+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:13.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:13.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:13.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.160 seconds
[2024-06-07T14:41:25.215+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:25.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:25.265+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:25.262+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:25.308+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:25.305+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:25.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:25.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.174 seconds
[2024-06-07T14:41:36.776+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:36.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:36.790+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:36.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:36.981+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:36.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:36.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:37.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.305 seconds
[2024-06-07T14:41:47.530+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:47.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:47.533+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:47.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:47.571+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:47.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:47.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:47.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.122 seconds
[2024-06-07T14:41:57.858+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:57.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:41:57.861+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:57.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:57.891+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:41:57.886+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:41:57.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:41:57.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.120 seconds
[2024-06-07T14:42:08.074+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:08.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:42:08.077+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:08.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:08.139+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:08.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:42:08.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:08.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.303 seconds
[2024-06-07T14:42:19.039+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:19.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:42:19.042+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:19.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:19.057+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:19.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:42:19.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:19.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.150 seconds
[2024-06-07T14:42:29.672+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:29.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:42:29.675+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:29.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:29.690+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:29.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:42:29.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:30.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.954 seconds
[2024-06-07T14:42:41.077+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:41.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:42:41.080+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:41.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:41.099+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:41.095+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:42:41.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:41.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.474 seconds
[2024-06-07T14:42:51.727+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:51.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:42:51.731+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:51.730+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:51.749+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:42:51.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:42:51.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:42:52.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.797 seconds
[2024-06-07T14:43:03.007+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:03.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:03.010+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:03.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:03.027+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:03.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:03.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:03.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.131 seconds
[2024-06-07T14:43:13.348+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:13.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:13.355+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:13.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:13.375+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:13.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:13.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:13.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.076 seconds
[2024-06-07T14:43:23.695+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:23.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:23.698+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:23.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:23.712+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:23.709+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:23.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:23.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.121 seconds
[2024-06-07T14:43:34.389+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:34.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:34.392+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:34.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:34.410+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:34.406+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:34.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:34.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.203 seconds
[2024-06-07T14:43:44.781+0000] {processor.py:161} INFO - Started process (PID=483) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:44.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:44.783+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:44.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:44.798+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:44.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:44.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:47.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.401 seconds
[2024-06-07T14:43:57.339+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:57.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:43:57.355+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:57.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:57.378+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:43:57.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:43:57.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:43:57.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.112 seconds
[2024-06-07T14:44:13.659+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:13.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:44:13.663+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:44:13.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:15.331+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:44:14.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:44:15.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:17.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 4.089 seconds
[2024-06-07T14:44:28.539+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:28.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-06-07T14:44:28.543+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:44:28.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:28.585+0000] {logging_mixin.py:188} INFO - [2024-06-07T14:44:28.575+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 8, in <module>
    from scripts.data_extraction import Extract
ModuleNotFoundError: No module named 'scripts.data_extraction'
[2024-06-07T14:44:28.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-06-07T14:44:28.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.103 seconds
